- name: Update APT cache
  apt: update_cache=true
  when: ansible_distribution_release == 'trusty'

- name: Install common dependencies
  apt:
    name: ['ca-certificates']
  when: ansible_distribution_release == 'trusty'

- name: Install apt_key dependencies
  apt:
    name: ['python-urllib3', 'python-openssl', 'python-pyasn1', 'python-pip']
  when: ansible_distribution_release == 'trusty'

- name: Install apt_key dependencies
  pip:
    name: ndg-httpsclient
  when: ansible_distribution_release == 'trusty'

#https://www.apache.org/dist/cassandra/KEYS
#sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv-key 32F35CB2F546D93E
- name: Add repository key
  apt_key:
    url: "{{ repokey_apache | default('https://downloads.apache.org/cassandra/KEYS') }}"
    state: present

- name: Add repository
  apt_repository:
    repo: "{{ repourl_apache | default('deb https://debian.cassandra.apache.org 41x main') }}"
    state: present

- name: Update APT cache
  apt: update_cache=true

- name: Install python-software-properties package
  apt: pkg=python-software-properties state=present
  when: ansible_distribution == 'Ubuntu' and ( ansible_distribution_release == 'trusty' or ansible_distribution_release == 'xenial' )

- name: Install python-setuptools package
  apt: pkg=python-setuptools state=present
  when: ansible_distribution == 'Ubuntu' and ( ansible_distribution_release == 'trusty' or ansible_distribution_release == 'xenial' )

- name: Install OpenJDK Java 8
  apt: name=openjdk-8-jdk state=latest
  when: java_version is not defined or java_version == 8

- name: Uninstall OpenJDK Java 8
  apt: name=openjdk-8-jdk state=absent
  when: java_version is defined and java_version != 8

- name: Install OpenJDK Java 11
  apt: name=openjdk-11-jdk state=latest
  when: java_version == 11
