- name: Update APT cache
  apt: update_cache=true

- name: Install common dependencies
  apt:
    name: ['ca-certificates']
  when: ansible_distribution_release == 'trusty'

- name: Install apt_key dependencies
  apt:
    name: ['python-urllib3', 'python-openssl', 'python-pyasn1', 'python-pip']
  when: ansible_distribution_release == 'trusty'

- name: Install apt_key dependencies
  pip:
    name: ndg-httpsclient
  when: ansible_distribution_release == 'trusty'

- name: Add Datastax repository (DCE)
  apt_repository:
    repo: "{{ repourl_datastax_ce | default('deb http://debian.datastax.com/community stable main') }}"
    state: present
  when: install_version == "dce"

- name: Add Datastax repository (DSE)
  apt_repository:
    repo: "{{ repourl_datastax_se | default('deb http://{{ dse_username }}:{{ dse_password }}@debian.datastax.com/enterprise stable main') }}"
    state: present
  when:
    - install_version == "dse"
    - dse_username is defined and dse_password is defined

- name: Add Datastax repository key
  apt_key:
    url: "{{ repokey_datastax | default('http://debian.datastax.com/debian/repo_key') }}"
    state: present
  when: install_version == "dce" or install_version == "dse"

#https://www.apache.org/dist/cassandra/KEYS
#sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv-key 32F35CB2F546D93E
- name: Add Apache repository key
  apt_key:
    url: "{{ repokey_apache | default('https://downloads.apache.org/cassandra/KEYS') }}"
    state: present
  when: install_version == "apache"

- name: Add Apache repository (Apache)
  apt_repository:
    repo: "{{ repourl_apache | default('deb https://debian.cassandra.apache.org 30x main') }}"
    state: present
  when: install_version == "apache"

- name: Add OpenJDK Java PPA repo
  apt_repository:
    repo: "{{ repourl_openjdk_java | default('ppa:openjdk-r/ppa') }}"

- name: Update APT cache
  apt: update_cache=true

- name: Install python-software-properties package
  apt: pkg=python-software-properties state=present
  when: ansible_distribution == 'Ubuntu' and ( ansible_distribution_release == 'trusty' or ansible_distribution_release == 'xenial' )

- name: Install python-setuptools package
  apt: pkg=python-setuptools state=present

- name: Install OpenJDK Java
  apt: name=openjdk-8-jdk state=latest